// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-aItDLlUB57CdiZaqksST8TY_kROsWZk',
    appId: '1:1058987748490:web:aa72a276ccbe00ad2d9173',
    messagingSenderId: '1058987748490',
    projectId: 'novo-historians',
    authDomain: 'novo-historians.firebaseapp.com',
    storageBucket: 'novo-historians.firebasestorage.app',
    measurementId: 'G-2CSNZVF137',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBADG3XG9xcnWglZ5oLP_HXz4K9TgJzEfY',
    appId: '1:1058987748490:android:b710a898d0acecb42d9173',
    messagingSenderId: '1058987748490',
    projectId: 'novo-historians',
    storageBucket: 'novo-historians.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIIAIh3qi7iU0QScj8SWstqwEBjD3rcZI',
    appId: '1:1058987748490:ios:6ea3737b6480ac602d9173',
    messagingSenderId: '1058987748490',
    projectId: 'novo-historians',
    storageBucket: 'novo-historians.firebasestorage.app',
    iosBundleId: 'com.example.novoHistorians',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIIAIh3qi7iU0QScj8SWstqwEBjD3rcZI',
    appId: '1:1058987748490:ios:6ea3737b6480ac602d9173',
    messagingSenderId: '1058987748490',
    projectId: 'novo-historians',
    storageBucket: 'novo-historians.firebasestorage.app',
    iosBundleId: 'com.example.novoHistorians',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-aItDLlUB57CdiZaqksST8TY_kROsWZk',
    appId: '1:1058987748490:web:ad46015dfab7bcf92d9173',
    messagingSenderId: '1058987748490',
    projectId: 'novo-historians',
    authDomain: 'novo-historians.firebaseapp.com',
    storageBucket: 'novo-historians.firebasestorage.app',
    measurementId: 'G-ZPSTC3EV19',
  );
}
